services:
  pixelfin:
    build: .
    container_name: pixelfin-develop
    ports:
      - "1280:1280"
    environment:
      - TZ=Etc/UTC
    volumes:
      - ./output:/app/output
      - ./assets:/app/assets
      - ./data:/app/data
    restart: unless-stopped
