services:
  pixelfin:
    build: .
    container_name: pixelfin
    ports:
      - "1280:1280"
    volumes:
      - ./output:/app/output
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
